# Generated by Django 5.0.6 on 2024-06-05 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('human_resource', '0001_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginfor',
            name='booked_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookinginfor',
            name='booking_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookinginfor',
            name='guest_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.guest'),
        ),
        migrations.AddField(
            model_name='bookinginfor',
            name='saleman_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.employee'),
        ),
        migrations.AddField(
            model_name='bookinginfor',
            name='booking_source_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.bookingsource'),
        ),
        migrations.AddField(
            model_name='charges',
            name='account_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.accounttype'),
        ),
        migrations.AddField(
            model_name='bookinginfor',
            name='country_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.country'),
        ),
        migrations.AddField(
            model_name='paymenttraninfor',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.paymentmethod'),
        ),
        migrations.AddField(
            model_name='rentalinfor',
            name='charges',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.charges'),
        ),
        migrations.AddField(
            model_name='rentalinfor',
            name='new_hk_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_hk_status', to='booking.housekeepingstatus'),
        ),
        migrations.AddField(
            model_name='rentalinfor',
            name='old_hk_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_hk_status', to='booking.housekeepingstatus'),
        ),
        migrations.AddField(
            model_name='rentalinfor',
            name='room_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.room'),
        ),
        migrations.AddField(
            model_name='stayinfor',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.guest'),
        ),
        migrations.AddField(
            model_name='traninfor',
            name='booking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.bookinginfor'),
        ),
        migrations.AddField(
            model_name='traninfor',
            name='room_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.room'),
        ),
        migrations.AddField(
            model_name='stayinfor',
            name='tran_infor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.traninfor'),
        ),
        migrations.AddField(
            model_name='rentalinfor',
            name='tran_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.traninfor'),
        ),
        migrations.AddField(
            model_name='paymenttraninfor',
            name='booking_infor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.traninfor'),
        ),
    ]
