# Generated by Django 5.0.6 on 2024-06-05 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('adult_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('child_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='front-desk', max_length=255)),
                ('modified_by', models.CharField(default='front-desk', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MealChargeTranInfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_adult', models.IntegerField(default=1)),
                ('quantity_child', models.IntegerField(default=1)),
                ('is_booked_before', models.BooleanField(default=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('rent_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('rent_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='front-desk', max_length=255)),
                ('modified_by', models.CharField(default='front-desk', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('charge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.charges')),
                ('rental_infor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.rentalinfor')),
                ('tran_infor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.traninfor')),
                ('meal_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.mealcode')),
            ],
        ),
    ]
