# Generated by Django 5.0.6 on 2024-06-07 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_mealcode_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClotheCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='front-desk', max_length=255)),
                ('modified_by', models.CharField(default='front-desk', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LaundryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='front-desk', max_length=255)),
                ('modified_by', models.CharField(default='front-desk', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LaundryItemServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(default='images/default.png', upload_to='images/')),
                ('description', models.CharField(max_length=255)),
                ('cost', models.FloatField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='front-desk', max_length=255)),
                ('modified_by', models.CharField(default='front-desk', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('clothe_category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.clothecategory')),
                ('laundry_service_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.laundryservice')),
            ],
            options={
                'verbose_name_plural': 'LaundryItemServicePrices',
                'ordering': ('-created_date',),
            },
        ),
    ]
