# Generated by Django 5.0.6 on 2024-06-08 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_paymenttraninfor_payment_method'),
        ('service', '0003_clothecategory_laundryservice_and_more'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryExtraService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('cost', models.FloatField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='front-desk', max_length=255)),
                ('modified_by', models.CharField(default='front-desk', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LaundryTranInfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_items', models.IntegerField(blank=True, null=True)),
                ('amount_paid', models.FloatField()),
                ('amount_tax', models.FloatField()),
                ('total_amount_paid', models.FloatField()),
                ('guest_laundry_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='front-desk', max_length=255)),
                ('modified_by', models.CharField(default='front-desk', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('laundry_extra_service_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.laundryextraservice')),
                ('rental_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.rentalinfor')),
                ('room_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.room')),
                ('tran_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.traninfor')),
            ],
        ),
    ]
