# Generated by Django 5.0.6 on 2024-06-08 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_laundryextraservice_laundrytraninfor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laundrytraninfor',
            name='tran_id',
        ),
    ]
