# Generated by Django 5.0.6 on 2024-06-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_fbtype_fbmeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbmeal',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='fbmeal',
            name='created_by',
            field=models.CharField(default='admin', max_length=255),
        ),
        migrations.AlterField(
            model_name='fbmeal',
            name='modified_by',
            field=models.CharField(default='admin', max_length=255),
        ),
        migrations.AlterField(
            model_name='fbtype',
            name='created_by',
            field=models.CharField(default='admin', max_length=255),
        ),
        migrations.AlterField(
            model_name='fbtype',
            name='modified_by',
            field=models.CharField(default='admin', max_length=255),
        ),
    ]
