# Generated by Django 5.0.6 on 2024-06-10 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_paymenttraninfor_payment_method'),
        ('service', '0007_fbmeal_image_alter_fbmeal_created_by_and_more'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FBTranInfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.FloatField()),
                ('amount_tax', models.FloatField()),
                ('total_amount_paid', models.FloatField()),
                ('transaction_time', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='front-desk', max_length=255)),
                ('modified_by', models.CharField(default='front-desk', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('rental_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.rentalinfor')),
                ('room_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.room')),
            ],
        ),
    ]
