# Generated by Django 5.0.6 on 2024-06-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_fbtraninfor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealcode',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
